services:
  django_admin_debug:
    image: django_admin_debug
    build:
      context: .
      dockerfile: ./docker_data/django_admin/DockerfileDebug
    ports:
      - 8000:8000
      - 5678:5678
    env_file:
      - .env
    depends_on:
      - postgres
  
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PRIMARY_DB_NAME}
      POSTGRES_USER: ${PRIMARY_DB_USER}
      POSTGRES_PASSWORD: ${PRIMARY_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${PRIMARY_DB_PORT}:5432"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./docker_data/swagger/openapi.yaml:/swagger.yaml
    environment:
      SWAGGER_JSON: /swagger.yaml
    restart: always


volumes:
  postgres_data:
