version: '3'
services:
  app:
    build: app
    expose:
      - "8000"
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    volumes:
      - ./docker_data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker_data/nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - app
    ports:
      - "80:80"

  postgresql:
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql



